// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Dbfirst2.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Dbfirst2.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<int> DeleteEmployeeByIDAsync(int? employeeID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> DeleteProductByIDAsync(int? productId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SalesbyYearResult>> SalesbyYearAsync(DateTime? beginning_Date, DateTime? ending_Date, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SelectAllCategoriesResult>> SelectAllCategoriesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SelectALLEmployeesResult>> SelectALLEmployeesAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
